tools:
  - class_name: verl.tools.mcp_search_tool.MCPSearchTool
    config:
      rate_limit: 120
      timeout: 120
      type: mcp
    mcp:
      mcp_servers_config_path: eexamples/sglang_multiturn/config/tool_config/mcp_server.json
      # optional
      tool_selected_list: 
        - tavily_search_tool